{{- if .Values.locationService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.locationService.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.locationService.name }}
spec:
  type: {{ .Values.locationService.service.type }}
  ports:
  - port: {{ .Values.locationService.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.locationService.name }}
{{- end }}
