{{- if .Values.configServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.configServer.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.configServer.name }}
spec:
  replicas: {{ .Values.configServer.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.configServer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.configServer.name }}
    spec:
      containers:
      - name: {{ .Values.configServer.name }}
        image: "{{ .Values.configServer.image.repository }}:{{ .Values.configServer.image.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.configServer.service.port }}
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        resources:
          {{- toYaml .Values.configServer.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
{{- end }}
